/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.unison.sistemamonitoreo.Cliente;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author rober
 */
public class MainFrame extends javax.swing.JFrame {
    private CardLayout cardLayout;
    private JPanel contentPanel;
    private PanelInicios panelInicios;
    private PanelMonitores panelMonitores;
    private PanelHistoricos panelHistoricos;

    
    public static final Color AZUL_UNISON = new Color(0, 82, 158);
    public static final Color AZUL_OSCURO_UNISON = new Color(1, 82, 148);
    public static final Color DORADO_UNISON = new Color(248, 187, 0);
    public static final Color DORADO_OSCURO_UNISON = new Color(217, 158, 48);
    
    public MainFrame() {
        initComponents();
        configurarPaneles();
        this.setLocationRelativeTo(null);
    }
        private void configurarPaneles() {
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);
        
        panelInicios = new PanelInicios(this);
        panelMonitores = new PanelMonitores(this);
        panelHistoricos = new PanelHistoricos(this);
        
        contentPanel.add(panelInicios, "INICIO");
        contentPanel.add(panelMonitores, "MONITOR");
        contentPanel.add(panelHistoricos, "HISTORICO");
        
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(contentPanel, BorderLayout.CENTER);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Monitoreo - Universidad de Sonora");
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));  // ← AGREGAR ESTO
        setResizable(true);  // ← CAMBIAR A true
    
    pack();
        mostrarPanel("INICIO");
        
    }
    
        public void mostrarPanel(String nombrePanel) {
        cardLayout.show(contentPanel, nombrePanel);
    if (!nombrePanel.equals("MONITOR") && panelMonitores != null) {
        panelMonitores.detenerLectura();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Monitoreo");
        setMinimumSize(new java.awt.Dimension(1000, 700));

        setBounds(0, 0, 548, 444);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            // Configurar fuente global
            Font segoeUI = new Font("Segoe UI", Font.PLAIN, 13);
            UIManager.put("Button.font", segoeUI);
            UIManager.put("Label.font", segoeUI);
            UIManager.put("TextField.font", segoeUI);
            UIManager.put("TextArea.font", segoeUI);
            UIManager.put("ComboBox.font", segoeUI);
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("===========================================");
                System.out.println("  Sistema de Monitoreo - UNISON");
                System.out.println("  Cliente iniciado correctamente");
                System.out.println("===========================================");
                new MainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
